### ISSUE TITLE
OSError: [Errno 75] Value too large for defined data type

### ISSUE THREAD

**Issue by thatlarrypearson** [thatlarrypearson/FileSystemSearcher#3]
$ python3.8 FileSystemSearcher.py --volume=GlacierNationalPark --output_format=csv --output_file=${HOME}/GlacierNationalPark.csv /media/lbp/GlacierNationalPark
Traceback (most recent call last):
  File "FileSystemSearcher.py", line 251, in <module>
    main()
  File "FileSystemSearcher.py", line 241, in main
    for record in crawler.path_crawler(base_path):
  File "FileSystemSearcher.py", line 175, in __next__
    'dropbox_hash': dropbox_hash(p),
  File "FileSystemSearcher.py", line 23, in dropbox_hash
    chunk = f.read(HASH_BLOCK_SIZE)
OSError: [Errno 75] Value too large for defined data type
$

**Comment by thatlarrypearson** [comment]
Linux Mint
$ uname -a
Linux death-valley 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ python3.8 --version
Python 3.8.0
$

**Comment by thatlarrypearson** [comment]
**4 TB NTFS USB HD**
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/sdb2       3.7T  3.3T  389G  90% /media/lbp/GlacierNationalPark
$ mount
...
/dev/sdb2 on /media/lbp/GlacierNationalPark type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
$

**Comment by thatlarrypearson** [comment]
Instrumented ```dropbox_hash()``` and ```zip_dropbox_hash()``` so that if/when the error occurs again we have enough information to write a test program.  Also, when the error occurs, the dropbox_hash value in the output record will be an empty string.

**Comment by thatlarrypearson** [comment]
$ python3.8 FileSystemSearcher.py --volume=GlacierNationalPark --output_format=csv --output_file=${HOME}/GlacierNationalPark-1.csv /media/lbp/GlacierNationalPark
OSError: [Errno 75] Value too large for defined data type
File Name: **/media/lbp/GlacierNationalPark/CampFires-20191231/WIDEBODY/Backup Set 2019-10-09 101506/Backup Files 2019-10-09 101506/Backup files 3252.zip**
Hash List Length: **17**
...
$ 
$ head GlacierNationalPark-1.csv
created,dropbox_hash,file_name,full_path,hostname,mime_encoding,mime_type,modified,relative_path,**size**,suffix,volume
...
$
$ grep 'Backup Set 2019-10-09 101506/Backup Files 2019-10-09 101506/Backup files 3252.zip' GlacierNationalPark-1.csv
2020-01-02T09:10:55.317527+00:00,,Backup files 3252.zip,/media/lbp/GlacierNationalPark/CampFires-20191231/WIDEBODY/Backup Set 2019-10-09 101506/Backup Files 2019-10-09 101506/Backup files 3252.zip,death-valley,,application/zip,2019-10-10T00:11:26+00:00,CampFires-20191231/WIDEBODY/Backup Set 2019-10-09 101506/Backup Files 2019-10-09 101506/Backup files 3252.zip,**173407561**,.zip,GlacierNationalPark
$

HASH_BLOCK_SIZE is 4,194,304
file size is 173,407,561
42 total reads expected but only 17 succeeded.

**Comment by thatlarrypearson** [comment]
What I learned:  When reading large blocks in Python, if the block size being read is larger than the default Python buffer size, bad things can happen.  Might be a bug.  The solution is to turn off buffering which is done on the open statement - ```open(filename, 'r-b', 0) - by using zero for the buffer size.
