### ISSUE TITLE
FileNotFoundError: File "FileSystemSearcher.py", line 245, in __iter__

### ISSUE THREAD

**Issue by thatlarrypearson** [thatlarrypearson/FileSystemSearcher#4]
$ python3.8 FileSystemSearcher.py --volume=GCNP-Hiker --output_format=csv --output_file=${HOME}/GCNP-Hiker.csv /media/lbp/GCNP-Hiker --search_zip_files
ZipCrawler.__init__(Backup files 1.zip, GCNP-Hiker)
Traceback (most recent call last):
  File "FileSystemSearcher.py", line 366, in <module>
    main()
  File "FileSystemSearcher.py", line 360, in main
    main_loop(args, publish)
  File "FileSystemSearcher.py", line 311, in main_loop
    for record in zcrawler:
  File "FileSystemSearcher.py", line 245, in __iter__
    self.z_file = zipfile.ZipFile(self.file)
  File "/usr/local/lib/python3.8/zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'Backup files 1.zip'
$
$ tail GCNP-Hiker.csv
...
2019-12-30T08:16:16.046067+00:00,55e72d3ae9f13520ef0a6d8eaa4062cf16667de88ae1726a38f316e0e10cf0c9,Backup files 1.zip,/media/lbp/GCNP-Hiker/WIDEBODY/Backup Set 2019-12-28 185250/Backup Files 2019-12-28 185250/Backup files 1.zip,thx-1138,,application/zip,2019-12-28T19:54:28.074356+00:00,WIDEBODY/Backup Set 2019-12-28 185250/Backup Files 2019-12-28 185250/Backup files 1.zip,57694701,.zip,GCNP-Hiker
$

**Comment by thatlarrypearson** [comment]
Fixed one problem and found another. The full path is still wrong.
{
- "created": "2020-02-03T10:31:30+00:00",
- "dropbox_hash": "4a360fdeb123c2f739a7a8b939e81ab197f7d1c79c50fe2d3d14b895a8d2ec77",
- "file_name": "src/OSError.txt", 
- **"full_path": "zippy.zip/src/OSError.txt",** 
- "hostname": "widebody", 
- "mime_encoding": null, 
- "mime_type": "text/plain", 
- "modified": "2020-02-03T10:31:30+00:00", 
- "relative_path": "src/OSError.txt", 
- "size": 1110, 
- "suffix": ".txt", 
- "volume": null
},

**Comment by thatlarrypearson** [comment]
The fix for the above has uncovered another problem.  In the Windows 10 backups, some of the archive files are malformed like the one that caused this error.  The archive is less than 600 bytes and isn't the only malformed on in the bunch.

$ python3.8 FileSystemSearcher.py --volume=GlacierNationalPark --output_format=csv --output_file=${HOME}/GlacierNationalPark-2.csv /media/lbp/GlacierNationalPark --search_zip_files
ZipCrawler.__init__(/media/lbp/GlacierNationalPark/CampFires-20191231/FileHistory/lbp/WIDEBODY/Data/$OF/36512/36513 (2019_10_10 15_31_14 UTC).zip, GlacierNationalPark)
Traceback (most recent call last):
  File "FileSystemSearcher.py", line 367, in <module>
    main()
  File "FileSystemSearcher.py", line 361, in main
    main_loop(args, publish)
  File "FileSystemSearcher.py", line 312, in main_loop
    for record in zcrawler:
  File "FileSystemSearcher.py", line 246, in __iter__
    self.z_file = zipfile.ZipFile(self.base_path)
  File "/usr/local/lib/python3.8/zipfile.py", line 1234, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.8/zipfile.py", line 1301, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
$
$
$ file '/media/lbp/GlacierNationalPark/CampFires-20191231/FileHistory/lbp/WIDEBODY/Data/$OF/36512/36513 (2019_10_10 15_31_14 UTC).zip'
/media/lbp/GlacierNationalPark/CampFires-20191231/FileHistory/lbp/WIDEBODY/Data/$OF/36512/36513 (2019_10_10 15_31_14 UTC).zip: zlib compressed data
$
$ tail GlacierNationalPark-2.csv
2020-01-01T23:31:02.394801+00:00,a5ea3ecdd87922522e45f864eac68ea0ccd86e7243070626fadcca1567eb92ee,36513 (2019_10_10 15_31_14 UTC).zip,/media/lbp/GlacierNationalPark/CampFires-20191231/FileHistory/lbp/WIDEBODY/Data/$OF/36512/36513 (2019_10_10 15_31_14 UTC).zip,death-valley,,application/zip,2017-02-04T00:13:12+00:00,CampFires-20191231/FileHistory/lbp/WIDEBODY/Data/$OF/36512/36513 (2019_10_10 15_31_14 UTC).zip,633,.zip,GlacierNationalPark
$
$ grep '.zip,' GlacierNationalPark-2.csv
2020-01-01T23:31:02.394801+00:00,a5ea3ecdd87922522e45f864eac68ea0ccd86e7243070626fadcca1567eb92ee,36513 (2019_10_10 15_31_14 UTC).zip,/media/lbp/GlacierNationalPark/CampFires-20191231/FileHistory/lbp/WIDEBODY/Data/$OF/36512/36513 (2019_10_10 15_31_14 UTC).zip,death-valley,,application/zip,2017-02-04T00:13:12+00:00,CampFires-20191231/FileHistory/lbp/WIDEBODY/Data/$OF/36512/36513 (2019_10_10 15_31_14 UTC).zip,633,.zip,GlacierNationalPark
$

**Comment by thatlarrypearson** [comment]
Fixed!
